### ISSUE TITLE
Arrows not visible under Firefox 

### ISSUE THREAD

**Issue by thechinese** [UST-MICO/grapheditor#2]
Tested with Firefox Version 67.0.4 (64-bit)
The arrows between the different interfaces of the deployed services or the arrows between the services themselves are not visible under firefox.
Sometimes, arrows from the application to the services are visible after moving the service or zooming.
The arrows from the interfaces to the respective services are sometimes visible if you hover over them.
Works fine under chrome

**Comment by buehlefs** [comment]
Fixed in 0.1.2
