### ISSUE TITLE
Links for Nodes with round edges should start at the rounded edge

### ISSUE THREAD

**Issue by manuwei** [UST-MICO/grapheditor#6]
![rounded edges](https://user-images.githubusercontent.com/44226745/69326765-a4ca7180-0c4c-11ea-93ce-09c5dc5976fd.png)

Edges for nodes with <rect> as templates begin in the edges of the underlying rectangle - this looks weird if we style the edges of the rect, e.g.: 
`<rect` x="0" y="0" width="100" height="40" rx="5" ry="5" `style="stroke:black;stroke-width:1;opacity:0.5">`
--> See screenshot
It would be nice to take this property of the node into account when placing the edges

**Comment by buehlefs** [comment]
The link handles are only computed once for a template. Styling information from css may not be available at that time. Also the styling may change dynamically as classes can be changed every render.

There are a number of ways to change the link handles for a template:
* Set `data-link-handles` to edges to get rid of the link handles in the corner ([documantation](https://mico-grapheditor.readthedocs.io/en/stable/grapheditor.html#link-handles))
* Use a (invisible) `<polygon>` as background
